language: node_js

node_js:
  - '0.12'
  - '0.10'
sudo: true # Enable docker-based containers
cache:
  directories: # Cache dependencies
    - node_modules

script:
  - npm test

services:
  - elasticsearch

before_script:
  - sleep 10
