language: node_js

node_js:
  - '0.12'
  - '0.10'
sudo: false # Enable docker-based containers
cache:
  directories: # Cache dependencies
    - node_modules

script:
  - npm test

services:
  - elasticsearch

before_script:
  - curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.3.4.deb && sudo dpkg -i --force-confnew elasticsearch-1.3.4.deb
  - sleep 10
